apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-crud
  template:
    metadata:
      labels:
        app: test-crud
    spec:
      containers:
      - name: test-crud-k8s-pod
        image: test-crud-image:latest